# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.network :forwarded_port, guest: 3306, host: 3306
  
  #Install MySQL
  config.vm.provision :shell, :path => "./scripts/mysql.sh"
  
  #Install Node.JS
  config.vm.provision :shell, :path => "./scripts/nodejs.sh"
  
  # Setup environment, download the dependencies etc
  config.vm.provision :shell, :path => "./scripts/setup_environment.sh"
  
  config.vm.synced_folder "../", "/project", :mount_options => ["dmode=777", "fmode=666"]
  config.vm.network "private_network", ip: "33.33.33.10"
end